### ISSUE TITLE
Wrong BDTH conversion

### ISSUE THREAD

**Issue by Lanselotto** [Bluefissure/HousingPos#3] opened 2021-03-27 17:37 UTC
value like 4.600 become 46.000 in BDTH when i press set.

**Comment by Bluefissure** [comment] 2021-03-28 02:23
That's probably caused by the differece in Germany/France system in denoting numbers.
Will fix in the next version.

**Comment by Bluefissure** [comment] 2021-03-28 03:59
Should be fixed in v1.0.7.0, you can use the update button in dalamud plugin manager to update.
If the problem persists, please reopen this issue.

**Closed as completed by Bluefissure** 2021-03-28 03:59 UTC
